name = "Lax842588"
defaultTargets = ["Lax842588"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax146103"
git = "https://github.com/szymtor/MSO-automata"
rev = "a850aa03d9cb3bff8aec3990269c99942ac56aff"
subDir = "concepts"


[[require]]
name = "Lax560851"
git = "https://github.com/szymtor/lax58"
rev = "2748fdc0afc0b4f729b7775ca6475ba08129418a"
subDir = "concepts"

[[lean_lib]]
name = "Lax842588"

[[require]]
name = "Lax808846"
git = "https://github.com/lax-archive/lax-submissions"
rev = "9394e531cc51cb67a0214bca3f9264dfe97ba5c7"
subDir = "word-ram/concepts"
