name = "Lax842588"
defaultTargets = ["Lax842588"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax146103"
git = "https://github.com/szymtor/MSO-automata"
rev = "b7b157e93741492b33a0fa84ec76e24a571e2a98"
subDir = "concepts"


[[require]]
name = "Lax560851"
git = "https://github.com/szymtor/lax58"
rev = "8ec635640f3fd05271fa5cb7b1d3ae9e59400d7b"
subDir = "concepts"

[[lean_lib]]
name = "Lax842588"

[[require]]
name = "Lax808846"
git = "https://github.com/lax-archive/lax-submissions"
rev = "9394e531cc51cb67a0214bca3f9264dfe97ba5c7"
subDir = "word-ram/concepts"
