import Lax842588Proofs.AutomatonRamArenaProgram
import Lax560851.StructuralCombinators

/-!
Proof-only IMP+ access routines for the distinguished uniform MSO input.
The public input is still the constructor-derived Lax-58 arena; these names
and pointer offsets are charged implementation details.
-/

namespace Lax842588Proofs.MSORamArenaProgram

open Lax759944Proofs.Legacy.Imp
open Lax842588Proofs.AutomatonRamProgram
open Lax842588Proofs.AutomatonRamArenaProgram
open Lax560851.StructuralCombinators

private abbrev lit (n : Nat) : Expr := .lit n
private abbrev var (x : String) : Expr := .var x
private abbrev get (a : String) (i : Expr) : Expr := .get a i
private abbrev add (x y : Expr) : Expr := .add x y
private abbrev sub (x y : Expr) : Expr := .sub x y
private abbrev eq (x y : Expr) : Cond := .eq x y
private abbrev lt (x y : Expr) : Cond := .lt x y
private abbrev inc (x : String) : Com := .assign x (add (var x) (lit 1))

/-- Follow the fixed three-field spine of
`msoModelChecking(alphabet, sentence, tree)`. -/
def openInstance : Com := seqs [
  .assign "instanceFields" (get "Arena" (add (var "root") (lit 2))),
  .assign "alphabetCursor"
    (get "Arena" (add (var "instanceFields") (lit 1))),
  .assign "formulaFieldTail"
    (get "Arena" (add (var "instanceFields") (lit 2))),
  .assign "formulaRoot"
    (get "Arena" (add (var "formulaFieldTail") (lit 1))),
  .assign "treeFieldTail"
    (get "Arena" (add (var "formulaFieldTail") (lit 2))),
  .assign "treeRoot"
    (get "Arena" (add (var "treeFieldTail") (lit 1)))]

/-- Fixed symbolic constructor tags used only by the proof-private arena
reader. They are generated by Lax-58's named-constructor combinator. -/
def orTag : Nat := Raw.constructorNameCode "or"
def negTag : Nat := Raw.constructorNameCode "neg"
def exFOTag : Nat := Raw.constructorNameCode "exFO"
def exSOTag : Nat := Raw.constructorNameCode "exSO"

/-- Load the top formula traversal frame and the symbolic constructor tag of
its represented intrinsic formula. -/
def loadFormulaFrame : Com := seqs [
  .assign "formulaIndex" (sub (var "formulaDepth") (lit 1)),
  .assign "currentFormula"
    (get "FormulaRootStack" (var "formulaIndex")),
  .assign "currentFO" (get "FormulaFOStack" (var "formulaIndex")),
  .assign "currentSO" (get "FormulaSOStack" (var "formulaIndex")),
  .assign "formulaPhase" (get "FormulaPhaseStack" (var "formulaIndex")),
  .assign "formulaNameRoot"
    (get "Arena" (add (var "currentFormula") (lit 1))),
  .assign "formulaTag"
    (get "Arena" (add (var "formulaNameRoot") (lit 1)))]

/-- Append the current formula occurrence to the postorder arrays and pop its
traversal frame. -/
def emitFormula : Com := seqs [
  .store "FormulaOrder" (var "formulaCount") (var "currentFormula"),
  .store "FormulaFOOrder" (var "formulaCount") (var "currentFO"),
  .store "FormulaSOOrder" (var "formulaCount") (var "currentSO"),
  inc "formulaCount",
  .assign "formulaDepth" (var "formulaIndex")]

/-- Locate the fields of the current named formula constructor. -/
def openFormulaFields : Com :=
  .assign "formulaFields"
    (get "Arena" (add (var "currentFormula") (lit 2)))

/-- Mark the current unary constructor ready to emit, then push its body with
the requested first- and second-order scope. -/
def pushUnaryBody (bodyFO bodySO : Expr) : Com := seqs [
  .store "FormulaPhaseStack" (var "formulaIndex") (lit 1),
  openFormulaFields,
  .assign "formulaChild"
    (get "Arena" (add (var "formulaFields") (lit 1))),
  .store "FormulaRootStack" (var "formulaDepth") (var "formulaChild"),
  .store "FormulaFOStack" (var "formulaDepth") bodyFO,
  .store "FormulaSOStack" (var "formulaDepth") bodySO,
  .store "FormulaPhaseStack" (var "formulaDepth") (lit 0),
  inc "formulaDepth"]

/-- Mark a disjunction after selecting its left child and push that child. -/
def pushOrLeft : Com := seqs [
  .store "FormulaPhaseStack" (var "formulaIndex") (lit 1),
  openFormulaFields,
  .assign "formulaChild"
    (get "Arena" (add (var "formulaFields") (lit 1))),
  .store "FormulaRootStack" (var "formulaDepth") (var "formulaChild"),
  .store "FormulaFOStack" (var "formulaDepth") (var "currentFO"),
  .store "FormulaSOStack" (var "formulaDepth") (var "currentSO"),
  .store "FormulaPhaseStack" (var "formulaDepth") (lit 0),
  inc "formulaDepth"]

/-- Select and push the right child of a disjunction whose left child has
already been emitted. -/
def pushOrRight : Com := seqs [
  .store "FormulaPhaseStack" (var "formulaIndex") (lit 2),
  openFormulaFields,
  .assign "formulaRightTail"
    (get "Arena" (add (var "formulaFields") (lit 2))),
  .assign "formulaChild"
    (get "Arena" (add (var "formulaRightTail") (lit 1))),
  .store "FormulaRootStack" (var "formulaDepth") (var "formulaChild"),
  .store "FormulaFOStack" (var "formulaDepth") (var "currentFO"),
  .store "FormulaSOStack" (var "formulaDepth") (var "currentSO"),
  .store "FormulaPhaseStack" (var "formulaDepth") (lit 0),
  inc "formulaDepth"]

/-- First visit to one formula occurrence. Atomic formulas emit immediately;
compound constructors push the next intrinsic subformula and its scope. -/
def enterFormula : Com :=
  .ite (eq (var "formulaTag") (lit orTag)) pushOrLeft
    (.ite (eq (var "formulaTag") (lit negTag))
      (pushUnaryBody (var "currentFO") (var "currentSO"))
      (.ite (eq (var "formulaTag") (lit exFOTag))
        (pushUnaryBody (add (var "currentFO") (lit 1)) (var "currentSO"))
        (.ite (eq (var "formulaTag") (lit exSOTag))
          (pushUnaryBody (var "currentFO")
            (add (var "currentSO") (lit 1)))
          emitFormula)))

/-- Revisit after one or more children. Only a phase-one disjunction still
has a child to visit; every other revisited constructor is ready to emit. -/
def revisitFormula : Com :=
  .ite (eq (var "formulaTag") (lit orTag))
    (.ite (eq (var "formulaPhase") (lit 1)) pushOrRight emitFormula)
    emitFormula

def formulaTraversalBody : Com := seqs [
  loadFormulaFrame,
  .ite (eq (var "formulaPhase") (lit 0)) enterFormula revisitFormula,
  inc "formulaSteps"]

def formulaTraversalLoop : Com :=
  .while (lt (lit 0) (var "formulaDepth")) formulaTraversalBody

/-- Initialize the explicit formula traversal stack with the sentence root at
the intrinsically empty scope. -/
def initializeFormulaTraversal : Com := seqs [
  .assign "formulaCount" (lit 0),
  .assign "formulaSteps" (lit 0),
  .assign "formulaDepth" (lit 1),
  .store "FormulaRootStack" (lit 0) (var "formulaRoot"),
  .store "FormulaFOStack" (lit 0) (lit 0),
  .store "FormulaSOStack" (lit 0) (lit 0),
  .store "FormulaPhaseStack" (lit 0) (lit 0)]

/-- Enumerate every intrinsic formula occurrence in postorder, carrying its
intrinsic first- and second-order scope alongside its arena address. -/
def readFormula : Com :=
  .seq initializeFormulaTraversal formulaTraversalLoop

end Lax842588Proofs.MSORamArenaProgram
