import Lax842588Proofs.EncodedPrimitiveAtomicAutomata
import Lax842588Proofs.SparseDeterministicAutomaton

/-!
Sparse deterministic presentations of the nontrivial primitive automata.
Their parent states are computed arithmetically from the marked symbol and
child row, matching the form generated by the charged RAM compiler.
-/

set_option backward.isDefEq.respectTransparency false

namespace Lax842588Proofs.SparsePrimitiveAtomicAutomata

open Lax842588.ValueTranslations
open Lax842588Proofs.EncodedPrimitiveAtomicAutomata
open Lax842588Proofs.FiniteAutomatonEncoding
open Lax842588Proofs.SparseDeterministicAutomaton

def validDigits (n m a : Nat) (children : List Nat) : List Nat :=
  (List.range n).map fun x =>
    occurrenceStep (foMarked n m a x)
      (children.map fun child => wordDigit 3 n child x)

@[simp] theorem validDigits_length (n m a : Nat) (children : List Nat) :
    (validDigits n m a children).length = n := by
  simp [validDigits]

theorem occurrenceStep_lt_three (atRoot : Bool) (digits : List Nat) :
    occurrenceStep atRoot digits < 3 := by
  unfold occurrenceStep
  split
  · omega
  · split <;> omega

theorem validDigits_value_lt_three {n m a : Nat} {children : List Nat}
    {value : Nat} (hvalue : value ∈ validDigits n m a children) :
    value < 3 := by
  simp only [validDigits, List.mem_map] at hvalue
  obtain ⟨x, _, rfl⟩ := hvalue
  exact occurrenceStep_lt_three _ _

def validParentP (n m a : Nat) (children : List Nat) : Nat :=
  radixValue 3 (validDigits n m a children)

theorem validParentP_lt (n m a : Nat) (children : List Nat) :
    validParentP n m a children < (words 3 n).length := by
  rw [words_length]
  simpa [validParentP] using
    (radixValue_lt_pow (digits := validDigits n m a children) (by omega)
      (fun value hvalue => validDigits_value_lt_three hvalue))

theorem radixWord_validParentP (n m a : Nat) (children : List Nat) :
    radixWord 3 n (validParentP n m a children) =
      validDigits n m a children := by
  simpa [validParentP] using
    (radixWord_radixValue 3 (validDigits n m a children) (by omega)
      (fun value hvalue => validDigits_value_lt_three hvalue))

theorem wordDigit_eq_radixWord_getD (base length state position : Nat)
    (hstate : state < base ^ length) :
    wordDigit base length state position =
      (radixWord base length state).getD position 0 := by
  unfold wordDigit
  rw [words_getD_eq_radixWord base length state hstate]

theorem validTransitionP_eq_parent (n m a q : Nat)
    (children : List Nat) (hqBound : q < (words 3 n).length) :
    validTransitionP n m a q children =
      decide (q = validParentP n m a children) := by
  apply Bool.eq_iff_iff.mpr
  simp only [validTransitionP, List.all_eq_true, decide_eq_true_eq]
  have hqPow : q < 3 ^ n := by simpa [words_length] using hqBound
  constructor
  · intro h
    have hword : radixWord 3 n q = validDigits n m a children := by
      apply List.ext_get
      · simp
      · intro i hiWord hiDigits
        have hi : i < n := by simpa using hiWord
        have heq := h i (List.mem_range.mpr hi)
        rw [wordDigit_eq_radixWord_getD 3 n q i hqPow] at heq
        rw [List.getD_eq_getElem (l := radixWord 3 n q) (d := 0)
          (by simpa using hi)] at heq
        simpa [validDigits, hi] using heq
    calc
      q = radixValue 3 (radixWord 3 n q) := by
        rw [radixValue_radixWord 3 n q (by omega) hqPow]
      _ = radixValue 3 (validDigits n m a children) := congrArg _ hword
      _ = validParentP n m a children := rfl
  · intro hqEq x hx
    have hx' : x < n := List.mem_range.mp hx
    rw [hqEq, wordDigit_eq_radixWord_getD 3 n
      (validParentP n m a children) x (by
        simpa [words_length] using validParentP_lt n m a children)]
    rw [radixWord_validParentP]
    simp [validDigits, hx']

def sparseValidCodeP (alphabet : RankedAlphabetCode) (n m : Nat) :
    AutomatonCode :=
  Lax842588Proofs.SparseDeterministicAutomaton.code
    (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)
    (words 3 n).length (validParentP n m) (validAcceptP n)

theorem sparseValid_toAutomaton_eq_validCodeP
    (alphabet : RankedAlphabetCode) (n m : Nat) :
    (sparseValidCodeP alphabet n m).toAutomaton
        (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m) =
      (validCodeP alphabet n m).toAutomaton
        (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m) := by
  let left :=
    (sparseValidCodeP alphabet n m).toAutomaton
      (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)
  let right :=
    (validCodeP alphabet n m).toAutomaton
      (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)
  change left = right
  have ht : left.transition = right.transition := by
    funext a q children
    change
      ((sparseValidCodeP alphabet n m).toAutomaton
          (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)).transition
            a q children =
        ((validCodeP alphabet n m).toAutomaton
          (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)).transition
            a q children
    unfold sparseValidCodeP
    rw [Lax842588Proofs.SparseDeterministicAutomaton.transition_code]
    unfold validCodeP
    rw [Lax842588Proofs.FiniteAutomatonEncoding.transition_encode]
    exact (validTransitionP_eq_parent n m a.val q.val
      (List.ofFn fun i => (children i).val) q.isLt).symm
  have ha : left.accept = right.accept := by
    funext q
    change
      ((sparseValidCodeP alphabet n m).toAutomaton
          (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)).accept q =
        ((validCodeP alphabet n m).toAutomaton
          (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)).accept q
    unfold sparseValidCodeP
    rw [Lax842588Proofs.SparseDeterministicAutomaton.accept_code]
    unfold validCodeP
    rw [Lax842588Proofs.FiniteAutomatonEncoding.accept_encode]
  rcases left with ⟨lt, la⟩
  rcases right with ⟨rt, ra⟩
  exact congrArg₂ Lax842588.TreeAutomaton.Automaton.mk ht ha

theorem sparseValidCodeP_accepts_iff_validCodeP
    (alphabet : RankedAlphabetCode) (n m : Nat)
    (t : Lax842588.RankedTree.Tree
      (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m).toRankedAlphabet) :
    ((sparseValidCodeP alphabet n m).toAutomaton
        (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)).Accepts t ↔
      ((validCodeP alphabet n m).toAutomaton
        (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)).Accepts t := by
  rw [sparseValid_toAutomaton_eq_validCodeP]

theorem sparseValidCodeP_accepts_iff
    (alphabet : RankedAlphabetCode) (n m : Nat)
    (t : Lax842588.RankedTree.Tree
      (Lax842588Proofs.MarkedTrees.MarkedAlphabet
        alphabet.toRankedAlphabet n m)) :
    ((sparseValidCodeP alphabet n m).toAutomaton
      (Lax842588Proofs.MarkedAlphabetEncoding.code alphabet n m)).Accepts
        (Lax842588Proofs.EncodedAtomicAutomata.codeTree alphabet n m t) ↔
      t ∈ Lax842588Proofs.MarkedTrees.validMarkedLanguage
        alphabet.toRankedAlphabet n m := by
  rw [sparseValid_toAutomaton_eq_validCodeP]
  exact validCodeP_accepts_iff alphabet n m t

end Lax842588Proofs.SparsePrimitiveAtomicAutomata
